import styles from "../calculator.module.css";
export function EligibilityContent() {
    return(
    <section className="content">
        <div className="container">
          <div className={styles.eligible}>
            
            <p>AI-backed Urban Money Business Loan Eligibility Calculator fast-forwards the process of selecting business mortgages. It assists in breaking down an array of factors and provides the best solution to meet the applicant&apos;s needs directly.</p>
            <p>Every business needs enough capital to back its core operations to stay in the industry. With the possibility of financial assistance, companies can stay focused on meeting their core needs. These needs could range from acquiring new equipment to hiring more talents, expanding ventures to availing new inventories, etc. Whatever the case may be, one cannot deny the importance of cash flow in the business.</p>
            <p>There are various ways one can fund his business, and undeniably the most common way is to get a business loan. Various banks and NBFCs provide business loans and usually differ in numerous factors. Consequently, it can get overwhelming to decide what kind of loan to get. The Urban Money Business Loan Eligibility Calculator helps you straighten things out.</p>  
            <h2 className="mt30 mb15 font18 text181d fontMedium">Business Loan Eligibility Calculator Formula</h2>
            <p>Urban Money uses a basic foolproof formula for calculating business loans, reducing the hassle to opt for a loan to a great extent. The calculator takes information such as age, net profit income, outstanding monthly credit payments (if any), maturity period and interest rate. Based on these inputs, the Urban Money Loan Eligibility Checker makes necessary analysis with precision using its powerful AI.</p>
            <p>You may use the results generated by Urban Money AI and cross-reference them with the factors that might affect your loan amount, such as your current profession, gross annual income, current city of residence, etc.,</p>
            <p>For example, you may get up to INR 40 Crore business loan at a starting interest rate of 8.85% per annum for a maturity period of up to 120 months. There will be an additional processing fee of up to 6.5% applied to the borrowed loan amount.</p>
            <p>The Urban Money Business Loan Eligibility Calculator can help you weigh the pros and cons of taking such a hefty loan by now only notifying you of your eligibility but also your EMI repayment capacity.</p>
            <h2 className="mt30 mb15 font18 text181d fontMedium">How to Use Urban Money Business Loan Eligibility Calculator?</h2>
            <p>The Urban Money Business Loan Eligibility Calculator helps the applicant bypass the research required to boil down a few pointers, such as the ideal business loan type to opt for, your eligibility to apply for one, repayment capability, the need for collateral, etc. </p>
            <p>When you land on the Urban Money Business Loan Eligibility Checker, you will be asked to enter the following data to help the AI determine your eligibility: </p>
              <ul className="oList blueList listSpanbold mb20">
                <li>Your residential address and date of birth.</li>
                <li>Your Age.<span className="fontStyleItalic">[<span className="fontBold">Note:</span> The applicant needs to be a minimum of 22 years of age at the time of applying and a maximum of 65 of age at the time of the final date for payment of a loan.]</span></li>
                <li>Your Net Profit.</li>
                <li>Your total monthly outstanding credit payments.  </li>
            </ul>
            <p>Once you enter all these details, you will have more options that can be manipulated, such as maturity period and interest rate.</p>

              <h2 className="mt30 mb15 font18 text181d fontMedium">Factors Affecting Business Loan Eligibility</h2>
            <p>The goal of any startup or business seeking financial aid is to avail of business loans without any hassle. But unfortunately, it is not that simple. Several factors affect a company&apos;s business loan eligibility. And even more so, it has a lot to do with the company or individual&apos;s financial choices and behavioural patterns. Some of these factors are as follows:</p>
            <h2 className="mt30 mb15 font18 text181d fontMedium">Credit History</h2>
            <ul>
              <li>It is a known fact that the applicant needs to have a good credit history.</li>
              <li>If someone has borrowed funds in the past and has successfully repaid the loan in time, there is a better chance of getting a loan approval than someone who has failed to repay it.</li>
              <li>A good credit score is measured with the tool known as the CIBIL score.</li>
              <li>Not only does it reflect a good credit history, but it also suggests good money management and smart spending habits.</li>
              <li>It has been agreed that a CIBIL score of over 750 is ideal for eligibility.</li>
            </ul>

            <h2 className="mt30 mb15 font18 text181d fontMedium">Performance</h2>
            <ul>
              <li>An exemplary business performance would be deemed ideal from the lender&apos;s perspective as it would suggest that the borrower holds the capability to repay the loan on time.</li>
              <li>Moreover, this can also mean that the lender may need assurances of a stable revenue turnover from the borrower to ensure that the loan can be potentially repaid without any unforeseen delays.</li>
              <li>Businesses consistently making a profit for the past two years received a positive response from lenders.</li>
            </ul>
            <h2 className="mt30 mb15 font18 text181d fontMedium">Experience</h2>
            <ul>
              <li>Banks usually prefer businesses to be at least 2-3 years old with decent business performance. There are some technical factors associated with the age of a business, such as the ability to produce income tax statements, bank statements and auditable accounts, among others.</li>
              <li>Lenders also consider the overall experience of the business owners. A minimum of 5 years can be a great added value for a business loan sanction.</li>
            </ul>
            <h2 className="mt30 mb15 font18 text181d fontMedium">Collateral</h2>
            <ul>
              <li>Often, it comes down to the need to attach collateral to receive a business loan, via which applicants stand a chance of getting their loans sanctioned.</li>
              <li>Properties in the name of an individual or business stand valuable for business loan eligibility in India.</li>
            </ul>
            <h2 className="mt30 mb15 font18 text181d fontMedium">Business Loan Eligibility Calculator Benefits</h2>
            <p>There are undeniable benefits of Urban Money&apos;s Business Loan Eligibility Calculator. To start with a few, we can say that the Urban Money Eligibility Checker is error-free, simple to use, and fast.</p>
            <p>As a growing business, time and accuracy are of utmost importance. And with an AI-backed calculator, there isn&apos;t much that can go wrong. Furthermore, it helps businesses understand the estimated amount of capital they can potentially receive, which can be beneficial in planning in advance.</p>

          </div>
        </div>
    </section>
    );
}